#!/usr/bin/env node
/**
 * Generate every brand asset the site needs from the one official mark.
 *
 *   npm run brand
 *
 * Input:  public/brand/wintora-mark.svg   (the leaf mark, two flat-filled paths)
 * Output: src/components/brand-mark.ts    (the paths, for the inline <svg> in Logo.tsx)
 *         src/app/icon.svg                (browser tab, crisp at any size)
 *         src/app/apple-icon.png           (180×180, white, iOS home screen)
 *         public/brand/icon-192.png        (PWA, transparent)
 *         public/brand/icon-512.png        (PWA, transparent)
 *         public/brand/icon-maskable-512.png (PWA maskable: Ice ground, safe padding)
 *
 * The mark is wider than it is tall and icons are square, so it is centred
 * on a square canvas with padding rather than stretched. Re-run whenever the
 * source file changes. The SVG is the source of truth; nothing reads a PNG.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import sharp from 'sharp';

const SOURCE = 'public/brand/wintora-mark.svg';

if (!existsSync(SOURCE)) {
  console.error(
    [
      `${SOURCE} not found.`,
      '',
      'Save the official leaf mark there as an SVG with two flat-filled paths',
      '(teal, then blue), then run this again.',
    ].join('\n'),
  );
  process.exit(1);
}

const svg = readFileSync(SOURCE, 'utf8');
const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
const paths = [...svg.matchAll(/<path[^>]*?fill="([^"]+)"[^>]*?d="([^"]+)"/g)].map((m) => ({ fill: m[1], d: m[2] }));
if (!viewBox || paths.length !== 2) {
  console.error(`Expected a viewBox and exactly two <path fill d> elements in ${SOURCE}; found ${paths.length}.`);
  process.exit(1);
}
const [x, y, w, h] = viewBox.split(/\s+/).map(Number);

// 1. The paths, as a module, so the mark is inline SVG everywhere.
writeFileSync(
  'src/components/brand-mark.ts',
  [
    '/**',
    ' * The Wintora mark as path data. Generated by `npm run brand` from',
    ' * public/brand/wintora-mark.svg; do not edit by hand.',
    ' */',
    '',
    `export const MARK_VIEWBOX = '${viewBox}';`,
    `export const MARK_WIDTH = ${w};`,
    `export const MARK_HEIGHT = ${h};`,
    `export const MARK_TEAL = '${paths[0].fill}';`,
    `export const MARK_BLUE = '${paths[1].fill}';`,
    'export const MARK_TEAL_PATH =',
    `  '${paths[0].d}';`,
    'export const MARK_BLUE_PATH =',
    `  '${paths[1].d}';`,
    '',
  ].join('\n'),
);

// 2. A square icon: the mark centred with padding.
function squareSvg({ pad, background }) {
  const side = Math.max(w, h) * (1 + pad * 2);
  const ox = x - (side - w) / 2;
  const oy = y - (side - h) / 2;
  const bg = background ? `<rect x="${ox}" y="${oy}" width="${side}" height="${side}" fill="${background}"/>` : '';
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${ox} ${oy} ${side} ${side}">${bg}<path fill="${paths[0].fill}" d="${paths[0].d}"/><path fill="${paths[1].fill}" d="${paths[1].d}"/></svg>`;
}

mkdirSync('src/app', { recursive: true });
mkdirSync('public/brand', { recursive: true });
writeFileSync('src/app/icon.svg', squareSvg({ pad: 0.08, background: null }) + '\n');

const raster = (markup, size, file, flatten) => {
  let img = sharp(Buffer.from(markup)).resize(size, size);
  if (flatten) img = img.flatten({ background: flatten });
  return img.png().toFile(file);
};

await raster(squareSvg({ pad: 0.14, background: null }), 180, 'src/app/apple-icon.png', '#ffffff');
await raster(squareSvg({ pad: 0.1, background: null }), 192, 'public/brand/icon-192.png');
await raster(squareSvg({ pad: 0.1, background: null }), 512, 'public/brand/icon-512.png');
await raster(squareSvg({ pad: 0.24, background: '#f4f8fa' }), 512, 'public/brand/icon-maskable-512.png');

console.log('Brand assets written: brand-mark.ts, icon.svg, apple-icon.png, icon-192/512, icon-maskable-512.');
